// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: rootstock/v1/rootstock.proto

package rootstockv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	v1 "rootstock/web-server/proto/rootstock/v1"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// HealthServiceName is the fully-qualified name of the HealthService service.
	HealthServiceName = "rootstock.v1.HealthService"
	// CampaignServiceName is the fully-qualified name of the CampaignService service.
	CampaignServiceName = "rootstock.v1.CampaignService"
	// OrgServiceName is the fully-qualified name of the OrgService service.
	OrgServiceName = "rootstock.v1.OrgService"
	// ScoreServiceName is the fully-qualified name of the ScoreService service.
	ScoreServiceName = "rootstock.v1.ScoreService"
	// DeviceServiceName is the fully-qualified name of the DeviceService service.
	DeviceServiceName = "rootstock.v1.DeviceService"
	// UserServiceName is the fully-qualified name of the UserService service.
	UserServiceName = "rootstock.v1.UserService"
	// ScitizenServiceName is the fully-qualified name of the ScitizenService service.
	ScitizenServiceName = "rootstock.v1.ScitizenService"
	// NotificationServiceName is the fully-qualified name of the NotificationService service.
	NotificationServiceName = "rootstock.v1.NotificationService"
	// AdminServiceName is the fully-qualified name of the AdminService service.
	AdminServiceName = "rootstock.v1.AdminService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// HealthServiceCheckProcedure is the fully-qualified name of the HealthService's Check RPC.
	HealthServiceCheckProcedure = "/rootstock.v1.HealthService/Check"
	// CampaignServiceCreateCampaignProcedure is the fully-qualified name of the CampaignService's
	// CreateCampaign RPC.
	CampaignServiceCreateCampaignProcedure = "/rootstock.v1.CampaignService/CreateCampaign"
	// CampaignServicePublishCampaignProcedure is the fully-qualified name of the CampaignService's
	// PublishCampaign RPC.
	CampaignServicePublishCampaignProcedure = "/rootstock.v1.CampaignService/PublishCampaign"
	// CampaignServiceListCampaignsProcedure is the fully-qualified name of the CampaignService's
	// ListCampaigns RPC.
	CampaignServiceListCampaignsProcedure = "/rootstock.v1.CampaignService/ListCampaigns"
	// CampaignServiceGetCampaignDashboardProcedure is the fully-qualified name of the CampaignService's
	// GetCampaignDashboard RPC.
	CampaignServiceGetCampaignDashboardProcedure = "/rootstock.v1.CampaignService/GetCampaignDashboard"
	// CampaignServiceExportCampaignDataProcedure is the fully-qualified name of the CampaignService's
	// ExportCampaignData RPC.
	CampaignServiceExportCampaignDataProcedure = "/rootstock.v1.CampaignService/ExportCampaignData"
	// OrgServiceCreateOrgProcedure is the fully-qualified name of the OrgService's CreateOrg RPC.
	OrgServiceCreateOrgProcedure = "/rootstock.v1.OrgService/CreateOrg"
	// OrgServiceNestOrgProcedure is the fully-qualified name of the OrgService's NestOrg RPC.
	OrgServiceNestOrgProcedure = "/rootstock.v1.OrgService/NestOrg"
	// OrgServiceDefineRoleProcedure is the fully-qualified name of the OrgService's DefineRole RPC.
	OrgServiceDefineRoleProcedure = "/rootstock.v1.OrgService/DefineRole"
	// OrgServiceAssignRoleProcedure is the fully-qualified name of the OrgService's AssignRole RPC.
	OrgServiceAssignRoleProcedure = "/rootstock.v1.OrgService/AssignRole"
	// OrgServiceInviteUserProcedure is the fully-qualified name of the OrgService's InviteUser RPC.
	OrgServiceInviteUserProcedure = "/rootstock.v1.OrgService/InviteUser"
	// ScoreServiceGetContributionProcedure is the fully-qualified name of the ScoreService's
	// GetContribution RPC.
	ScoreServiceGetContributionProcedure = "/rootstock.v1.ScoreService/GetContribution"
	// DeviceServiceGetDeviceProcedure is the fully-qualified name of the DeviceService's GetDevice RPC.
	DeviceServiceGetDeviceProcedure = "/rootstock.v1.DeviceService/GetDevice"
	// DeviceServiceRevokeDeviceProcedure is the fully-qualified name of the DeviceService's
	// RevokeDevice RPC.
	DeviceServiceRevokeDeviceProcedure = "/rootstock.v1.DeviceService/RevokeDevice"
	// DeviceServiceReinstateDeviceProcedure is the fully-qualified name of the DeviceService's
	// ReinstateDevice RPC.
	DeviceServiceReinstateDeviceProcedure = "/rootstock.v1.DeviceService/ReinstateDevice"
	// DeviceServiceEnrollInCampaignProcedure is the fully-qualified name of the DeviceService's
	// EnrollInCampaign RPC.
	DeviceServiceEnrollInCampaignProcedure = "/rootstock.v1.DeviceService/EnrollInCampaign"
	// UserServiceRegisterUserProcedure is the fully-qualified name of the UserService's RegisterUser
	// RPC.
	UserServiceRegisterUserProcedure = "/rootstock.v1.UserService/RegisterUser"
	// UserServiceGetMeProcedure is the fully-qualified name of the UserService's GetMe RPC.
	UserServiceGetMeProcedure = "/rootstock.v1.UserService/GetMe"
	// UserServiceLoginProcedure is the fully-qualified name of the UserService's Login RPC.
	UserServiceLoginProcedure = "/rootstock.v1.UserService/Login"
	// UserServiceLogoutProcedure is the fully-qualified name of the UserService's Logout RPC.
	UserServiceLogoutProcedure = "/rootstock.v1.UserService/Logout"
	// UserServiceRegisterResearcherProcedure is the fully-qualified name of the UserService's
	// RegisterResearcher RPC.
	UserServiceRegisterResearcherProcedure = "/rootstock.v1.UserService/RegisterResearcher"
	// UserServiceVerifyEmailProcedure is the fully-qualified name of the UserService's VerifyEmail RPC.
	UserServiceVerifyEmailProcedure = "/rootstock.v1.UserService/VerifyEmail"
	// ScitizenServiceRegisterScitizenProcedure is the fully-qualified name of the ScitizenService's
	// RegisterScitizen RPC.
	ScitizenServiceRegisterScitizenProcedure = "/rootstock.v1.ScitizenService/RegisterScitizen"
	// ScitizenServiceGetDashboardProcedure is the fully-qualified name of the ScitizenService's
	// GetDashboard RPC.
	ScitizenServiceGetDashboardProcedure = "/rootstock.v1.ScitizenService/GetDashboard"
	// ScitizenServiceBrowsePublishedCampaignsProcedure is the fully-qualified name of the
	// ScitizenService's BrowsePublishedCampaigns RPC.
	ScitizenServiceBrowsePublishedCampaignsProcedure = "/rootstock.v1.ScitizenService/BrowsePublishedCampaigns"
	// ScitizenServiceGetCampaignDetailProcedure is the fully-qualified name of the ScitizenService's
	// GetCampaignDetail RPC.
	ScitizenServiceGetCampaignDetailProcedure = "/rootstock.v1.ScitizenService/GetCampaignDetail"
	// ScitizenServiceSearchCampaignsProcedure is the fully-qualified name of the ScitizenService's
	// SearchCampaigns RPC.
	ScitizenServiceSearchCampaignsProcedure = "/rootstock.v1.ScitizenService/SearchCampaigns"
	// ScitizenServiceEnrollDeviceProcedure is the fully-qualified name of the ScitizenService's
	// EnrollDevice RPC.
	ScitizenServiceEnrollDeviceProcedure = "/rootstock.v1.ScitizenService/EnrollDevice"
	// ScitizenServiceWithdrawEnrollmentProcedure is the fully-qualified name of the ScitizenService's
	// WithdrawEnrollment RPC.
	ScitizenServiceWithdrawEnrollmentProcedure = "/rootstock.v1.ScitizenService/WithdrawEnrollment"
	// ScitizenServiceGetDevicesProcedure is the fully-qualified name of the ScitizenService's
	// GetDevices RPC.
	ScitizenServiceGetDevicesProcedure = "/rootstock.v1.ScitizenService/GetDevices"
	// ScitizenServiceGetDeviceDetailProcedure is the fully-qualified name of the ScitizenService's
	// GetDeviceDetail RPC.
	ScitizenServiceGetDeviceDetailProcedure = "/rootstock.v1.ScitizenService/GetDeviceDetail"
	// ScitizenServiceGetNotificationsProcedure is the fully-qualified name of the ScitizenService's
	// GetNotifications RPC.
	ScitizenServiceGetNotificationsProcedure = "/rootstock.v1.ScitizenService/GetNotifications"
	// ScitizenServiceGetContributionsProcedure is the fully-qualified name of the ScitizenService's
	// GetContributions RPC.
	ScitizenServiceGetContributionsProcedure = "/rootstock.v1.ScitizenService/GetContributions"
	// ScitizenServiceGetOnboardingStateProcedure is the fully-qualified name of the ScitizenService's
	// GetOnboardingState RPC.
	ScitizenServiceGetOnboardingStateProcedure = "/rootstock.v1.ScitizenService/GetOnboardingState"
	// NotificationServiceListNotificationsProcedure is the fully-qualified name of the
	// NotificationService's ListNotifications RPC.
	NotificationServiceListNotificationsProcedure = "/rootstock.v1.NotificationService/ListNotifications"
	// NotificationServiceMarkReadProcedure is the fully-qualified name of the NotificationService's
	// MarkRead RPC.
	NotificationServiceMarkReadProcedure = "/rootstock.v1.NotificationService/MarkRead"
	// NotificationServiceGetPreferencesProcedure is the fully-qualified name of the
	// NotificationService's GetPreferences RPC.
	NotificationServiceGetPreferencesProcedure = "/rootstock.v1.NotificationService/GetPreferences"
	// NotificationServiceUpdatePreferencesProcedure is the fully-qualified name of the
	// NotificationService's UpdatePreferences RPC.
	NotificationServiceUpdatePreferencesProcedure = "/rootstock.v1.NotificationService/UpdatePreferences"
	// AdminServiceSuspendByClassProcedure is the fully-qualified name of the AdminService's
	// SuspendByClass RPC.
	AdminServiceSuspendByClassProcedure = "/rootstock.v1.AdminService/SuspendByClass"
)

// HealthServiceClient is a client for the rootstock.v1.HealthService service.
type HealthServiceClient interface {
	Check(context.Context, *connect.Request[v1.CheckRequest]) (*connect.Response[v1.CheckResponse], error)
}

// NewHealthServiceClient constructs a client for the rootstock.v1.HealthService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewHealthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) HealthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	healthServiceMethods := v1.File_rootstock_v1_rootstock_proto.Services().ByName("HealthService").Methods()
	return &healthServiceClient{
		check: connect.NewClient[v1.CheckRequest, v1.CheckResponse](
			httpClient,
			baseURL+HealthServiceCheckProcedure,
			connect.WithSchema(healthServiceMethods.ByName("Check")),
			connect.WithClientOptions(opts...),
		),
	}
}

// healthServiceClient implements HealthServiceClient.
type healthServiceClient struct {
	check *connect.Client[v1.CheckRequest, v1.CheckResponse]
}

// Check calls rootstock.v1.HealthService.Check.
func (c *healthServiceClient) Check(ctx context.Context, req *connect.Request[v1.CheckRequest]) (*connect.Response[v1.CheckResponse], error) {
	return c.check.CallUnary(ctx, req)
}

// HealthServiceHandler is an implementation of the rootstock.v1.HealthService service.
type HealthServiceHandler interface {
	Check(context.Context, *connect.Request[v1.CheckRequest]) (*connect.Response[v1.CheckResponse], error)
}

// NewHealthServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewHealthServiceHandler(svc HealthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	healthServiceMethods := v1.File_rootstock_v1_rootstock_proto.Services().ByName("HealthService").Methods()
	healthServiceCheckHandler := connect.NewUnaryHandler(
		HealthServiceCheckProcedure,
		svc.Check,
		connect.WithSchema(healthServiceMethods.ByName("Check")),
		connect.WithHandlerOptions(opts...),
	)
	return "/rootstock.v1.HealthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case HealthServiceCheckProcedure:
			healthServiceCheckHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedHealthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedHealthServiceHandler struct{}

func (UnimplementedHealthServiceHandler) Check(context.Context, *connect.Request[v1.CheckRequest]) (*connect.Response[v1.CheckResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rootstock.v1.HealthService.Check is not implemented"))
}

// CampaignServiceClient is a client for the rootstock.v1.CampaignService service.
type CampaignServiceClient interface {
	CreateCampaign(context.Context, *connect.Request[v1.CreateCampaignRequest]) (*connect.Response[v1.CreateCampaignResponse], error)
	PublishCampaign(context.Context, *connect.Request[v1.PublishCampaignRequest]) (*connect.Response[v1.PublishCampaignResponse], error)
	ListCampaigns(context.Context, *connect.Request[v1.ListCampaignsRequest]) (*connect.Response[v1.ListCampaignsResponse], error)
	GetCampaignDashboard(context.Context, *connect.Request[v1.GetCampaignDashboardRequest]) (*connect.Response[v1.GetCampaignDashboardResponse], error)
	ExportCampaignData(context.Context, *connect.Request[v1.ExportCampaignDataRequest]) (*connect.Response[v1.ExportCampaignDataResponse], error)
}

// NewCampaignServiceClient constructs a client for the rootstock.v1.CampaignService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCampaignServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CampaignServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	campaignServiceMethods := v1.File_rootstock_v1_rootstock_proto.Services().ByName("CampaignService").Methods()
	return &campaignServiceClient{
		createCampaign: connect.NewClient[v1.CreateCampaignRequest, v1.CreateCampaignResponse](
			httpClient,
			baseURL+CampaignServiceCreateCampaignProcedure,
			connect.WithSchema(campaignServiceMethods.ByName("CreateCampaign")),
			connect.WithClientOptions(opts...),
		),
		publishCampaign: connect.NewClient[v1.PublishCampaignRequest, v1.PublishCampaignResponse](
			httpClient,
			baseURL+CampaignServicePublishCampaignProcedure,
			connect.WithSchema(campaignServiceMethods.ByName("PublishCampaign")),
			connect.WithClientOptions(opts...),
		),
		listCampaigns: connect.NewClient[v1.ListCampaignsRequest, v1.ListCampaignsResponse](
			httpClient,
			baseURL+CampaignServiceListCampaignsProcedure,
			connect.WithSchema(campaignServiceMethods.ByName("ListCampaigns")),
			connect.WithClientOptions(opts...),
		),
		getCampaignDashboard: connect.NewClient[v1.GetCampaignDashboardRequest, v1.GetCampaignDashboardResponse](
			httpClient,
			baseURL+CampaignServiceGetCampaignDashboardProcedure,
			connect.WithSchema(campaignServiceMethods.ByName("GetCampaignDashboard")),
			connect.WithClientOptions(opts...),
		),
		exportCampaignData: connect.NewClient[v1.ExportCampaignDataRequest, v1.ExportCampaignDataResponse](
			httpClient,
			baseURL+CampaignServiceExportCampaignDataProcedure,
			connect.WithSchema(campaignServiceMethods.ByName("ExportCampaignData")),
			connect.WithClientOptions(opts...),
		),
	}
}

// campaignServiceClient implements CampaignServiceClient.
type campaignServiceClient struct {
	createCampaign       *connect.Client[v1.CreateCampaignRequest, v1.CreateCampaignResponse]
	publishCampaign      *connect.Client[v1.PublishCampaignRequest, v1.PublishCampaignResponse]
	listCampaigns        *connect.Client[v1.ListCampaignsRequest, v1.ListCampaignsResponse]
	getCampaignDashboard *connect.Client[v1.GetCampaignDashboardRequest, v1.GetCampaignDashboardResponse]
	exportCampaignData   *connect.Client[v1.ExportCampaignDataRequest, v1.ExportCampaignDataResponse]
}

// CreateCampaign calls rootstock.v1.CampaignService.CreateCampaign.
func (c *campaignServiceClient) CreateCampaign(ctx context.Context, req *connect.Request[v1.CreateCampaignRequest]) (*connect.Response[v1.CreateCampaignResponse], error) {
	return c.createCampaign.CallUnary(ctx, req)
}

// PublishCampaign calls rootstock.v1.CampaignService.PublishCampaign.
func (c *campaignServiceClient) PublishCampaign(ctx context.Context, req *connect.Request[v1.PublishCampaignRequest]) (*connect.Response[v1.PublishCampaignResponse], error) {
	return c.publishCampaign.CallUnary(ctx, req)
}

// ListCampaigns calls rootstock.v1.CampaignService.ListCampaigns.
func (c *campaignServiceClient) ListCampaigns(ctx context.Context, req *connect.Request[v1.ListCampaignsRequest]) (*connect.Response[v1.ListCampaignsResponse], error) {
	return c.listCampaigns.CallUnary(ctx, req)
}

// GetCampaignDashboard calls rootstock.v1.CampaignService.GetCampaignDashboard.
func (c *campaignServiceClient) GetCampaignDashboard(ctx context.Context, req *connect.Request[v1.GetCampaignDashboardRequest]) (*connect.Response[v1.GetCampaignDashboardResponse], error) {
	return c.getCampaignDashboard.CallUnary(ctx, req)
}

// ExportCampaignData calls rootstock.v1.CampaignService.ExportCampaignData.
func (c *campaignServiceClient) ExportCampaignData(ctx context.Context, req *connect.Request[v1.ExportCampaignDataRequest]) (*connect.Response[v1.ExportCampaignDataResponse], error) {
	return c.exportCampaignData.CallUnary(ctx, req)
}

// CampaignServiceHandler is an implementation of the rootstock.v1.CampaignService service.
type CampaignServiceHandler interface {
	CreateCampaign(context.Context, *connect.Request[v1.CreateCampaignRequest]) (*connect.Response[v1.CreateCampaignResponse], error)
	PublishCampaign(context.Context, *connect.Request[v1.PublishCampaignRequest]) (*connect.Response[v1.PublishCampaignResponse], error)
	ListCampaigns(context.Context, *connect.Request[v1.ListCampaignsRequest]) (*connect.Response[v1.ListCampaignsResponse], error)
	GetCampaignDashboard(context.Context, *connect.Request[v1.GetCampaignDashboardRequest]) (*connect.Response[v1.GetCampaignDashboardResponse], error)
	ExportCampaignData(context.Context, *connect.Request[v1.ExportCampaignDataRequest]) (*connect.Response[v1.ExportCampaignDataResponse], error)
}

// NewCampaignServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCampaignServiceHandler(svc CampaignServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	campaignServiceMethods := v1.File_rootstock_v1_rootstock_proto.Services().ByName("CampaignService").Methods()
	campaignServiceCreateCampaignHandler := connect.NewUnaryHandler(
		CampaignServiceCreateCampaignProcedure,
		svc.CreateCampaign,
		connect.WithSchema(campaignServiceMethods.ByName("CreateCampaign")),
		connect.WithHandlerOptions(opts...),
	)
	campaignServicePublishCampaignHandler := connect.NewUnaryHandler(
		CampaignServicePublishCampaignProcedure,
		svc.PublishCampaign,
		connect.WithSchema(campaignServiceMethods.ByName("PublishCampaign")),
		connect.WithHandlerOptions(opts...),
	)
	campaignServiceListCampaignsHandler := connect.NewUnaryHandler(
		CampaignServiceListCampaignsProcedure,
		svc.ListCampaigns,
		connect.WithSchema(campaignServiceMethods.ByName("ListCampaigns")),
		connect.WithHandlerOptions(opts...),
	)
	campaignServiceGetCampaignDashboardHandler := connect.NewUnaryHandler(
		CampaignServiceGetCampaignDashboardProcedure,
		svc.GetCampaignDashboard,
		connect.WithSchema(campaignServiceMethods.ByName("GetCampaignDashboard")),
		connect.WithHandlerOptions(opts...),
	)
	campaignServiceExportCampaignDataHandler := connect.NewUnaryHandler(
		CampaignServiceExportCampaignDataProcedure,
		svc.ExportCampaignData,
		connect.WithSchema(campaignServiceMethods.ByName("ExportCampaignData")),
		connect.WithHandlerOptions(opts...),
	)
	return "/rootstock.v1.CampaignService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CampaignServiceCreateCampaignProcedure:
			campaignServiceCreateCampaignHandler.ServeHTTP(w, r)
		case CampaignServicePublishCampaignProcedure:
			campaignServicePublishCampaignHandler.ServeHTTP(w, r)
		case CampaignServiceListCampaignsProcedure:
			campaignServiceListCampaignsHandler.ServeHTTP(w, r)
		case CampaignServiceGetCampaignDashboardProcedure:
			campaignServiceGetCampaignDashboardHandler.ServeHTTP(w, r)
		case CampaignServiceExportCampaignDataProcedure:
			campaignServiceExportCampaignDataHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCampaignServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCampaignServiceHandler struct{}

func (UnimplementedCampaignServiceHandler) CreateCampaign(context.Context, *connect.Request[v1.CreateCampaignRequest]) (*connect.Response[v1.CreateCampaignResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rootstock.v1.CampaignService.CreateCampaign is not implemented"))
}

func (UnimplementedCampaignServiceHandler) PublishCampaign(context.Context, *connect.Request[v1.PublishCampaignRequest]) (*connect.Response[v1.PublishCampaignResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rootstock.v1.CampaignService.PublishCampaign is not implemented"))
}

func (UnimplementedCampaignServiceHandler) ListCampaigns(context.Context, *connect.Request[v1.ListCampaignsRequest]) (*connect.Response[v1.ListCampaignsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rootstock.v1.CampaignService.ListCampaigns is not implemented"))
}

func (UnimplementedCampaignServiceHandler) GetCampaignDashboard(context.Context, *connect.Request[v1.GetCampaignDashboardRequest]) (*connect.Response[v1.GetCampaignDashboardResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rootstock.v1.CampaignService.GetCampaignDashboard is not implemented"))
}

func (UnimplementedCampaignServiceHandler) ExportCampaignData(context.Context, *connect.Request[v1.ExportCampaignDataRequest]) (*connect.Response[v1.ExportCampaignDataResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rootstock.v1.CampaignService.ExportCampaignData is not implemented"))
}

// OrgServiceClient is a client for the rootstock.v1.OrgService service.
type OrgServiceClient interface {
	CreateOrg(context.Context, *connect.Request[v1.CreateOrgRequest]) (*connect.Response[v1.CreateOrgResponse], error)
	NestOrg(context.Context, *connect.Request[v1.NestOrgRequest]) (*connect.Response[v1.NestOrgResponse], error)
	DefineRole(context.Context, *connect.Request[v1.DefineRoleRequest]) (*connect.Response[v1.DefineRoleResponse], error)
	AssignRole(context.Context, *connect.Request[v1.AssignRoleRequest]) (*connect.Response[v1.AssignRoleResponse], error)
	InviteUser(context.Context, *connect.Request[v1.InviteUserRequest]) (*connect.Response[v1.InviteUserResponse], error)
}

// NewOrgServiceClient constructs a client for the rootstock.v1.OrgService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewOrgServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) OrgServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	orgServiceMethods := v1.File_rootstock_v1_rootstock_proto.Services().ByName("OrgService").Methods()
	return &orgServiceClient{
		createOrg: connect.NewClient[v1.CreateOrgRequest, v1.CreateOrgResponse](
			httpClient,
			baseURL+OrgServiceCreateOrgProcedure,
			connect.WithSchema(orgServiceMethods.ByName("CreateOrg")),
			connect.WithClientOptions(opts...),
		),
		nestOrg: connect.NewClient[v1.NestOrgRequest, v1.NestOrgResponse](
			httpClient,
			baseURL+OrgServiceNestOrgProcedure,
			connect.WithSchema(orgServiceMethods.ByName("NestOrg")),
			connect.WithClientOptions(opts...),
		),
		defineRole: connect.NewClient[v1.DefineRoleRequest, v1.DefineRoleResponse](
			httpClient,
			baseURL+OrgServiceDefineRoleProcedure,
			connect.WithSchema(orgServiceMethods.ByName("DefineRole")),
			connect.WithClientOptions(opts...),
		),
		assignRole: connect.NewClient[v1.AssignRoleRequest, v1.AssignRoleResponse](
			httpClient,
			baseURL+OrgServiceAssignRoleProcedure,
			connect.WithSchema(orgServiceMethods.ByName("AssignRole")),
			connect.WithClientOptions(opts...),
		),
		inviteUser: connect.NewClient[v1.InviteUserRequest, v1.InviteUserResponse](
			httpClient,
			baseURL+OrgServiceInviteUserProcedure,
			connect.WithSchema(orgServiceMethods.ByName("InviteUser")),
			connect.WithClientOptions(opts...),
		),
	}
}

// orgServiceClient implements OrgServiceClient.
type orgServiceClient struct {
	createOrg  *connect.Client[v1.CreateOrgRequest, v1.CreateOrgResponse]
	nestOrg    *connect.Client[v1.NestOrgRequest, v1.NestOrgResponse]
	defineRole *connect.Client[v1.DefineRoleRequest, v1.DefineRoleResponse]
	assignRole *connect.Client[v1.AssignRoleRequest, v1.AssignRoleResponse]
	inviteUser *connect.Client[v1.InviteUserRequest, v1.InviteUserResponse]
}

// CreateOrg calls rootstock.v1.OrgService.CreateOrg.
func (c *orgServiceClient) CreateOrg(ctx context.Context, req *connect.Request[v1.CreateOrgRequest]) (*connect.Response[v1.CreateOrgResponse], error) {
	return c.createOrg.CallUnary(ctx, req)
}

// NestOrg calls rootstock.v1.OrgService.NestOrg.
func (c *orgServiceClient) NestOrg(ctx context.Context, req *connect.Request[v1.NestOrgRequest]) (*connect.Response[v1.NestOrgResponse], error) {
	return c.nestOrg.CallUnary(ctx, req)
}

// DefineRole calls rootstock.v1.OrgService.DefineRole.
func (c *orgServiceClient) DefineRole(ctx context.Context, req *connect.Request[v1.DefineRoleRequest]) (*connect.Response[v1.DefineRoleResponse], error) {
	return c.defineRole.CallUnary(ctx, req)
}

// AssignRole calls rootstock.v1.OrgService.AssignRole.
func (c *orgServiceClient) AssignRole(ctx context.Context, req *connect.Request[v1.AssignRoleRequest]) (*connect.Response[v1.AssignRoleResponse], error) {
	return c.assignRole.CallUnary(ctx, req)
}

// InviteUser calls rootstock.v1.OrgService.InviteUser.
func (c *orgServiceClient) InviteUser(ctx context.Context, req *connect.Request[v1.InviteUserRequest]) (*connect.Response[v1.InviteUserResponse], error) {
	return c.inviteUser.CallUnary(ctx, req)
}

// OrgServiceHandler is an implementation of the rootstock.v1.OrgService service.
type OrgServiceHandler interface {
	CreateOrg(context.Context, *connect.Request[v1.CreateOrgRequest]) (*connect.Response[v1.CreateOrgResponse], error)
	NestOrg(context.Context, *connect.Request[v1.NestOrgRequest]) (*connect.Response[v1.NestOrgResponse], error)
	DefineRole(context.Context, *connect.Request[v1.DefineRoleRequest]) (*connect.Response[v1.DefineRoleResponse], error)
	AssignRole(context.Context, *connect.Request[v1.AssignRoleRequest]) (*connect.Response[v1.AssignRoleResponse], error)
	InviteUser(context.Context, *connect.Request[v1.InviteUserRequest]) (*connect.Response[v1.InviteUserResponse], error)
}

// NewOrgServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewOrgServiceHandler(svc OrgServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	orgServiceMethods := v1.File_rootstock_v1_rootstock_proto.Services().ByName("OrgService").Methods()
	orgServiceCreateOrgHandler := connect.NewUnaryHandler(
		OrgServiceCreateOrgProcedure,
		svc.CreateOrg,
		connect.WithSchema(orgServiceMethods.ByName("CreateOrg")),
		connect.WithHandlerOptions(opts...),
	)
	orgServiceNestOrgHandler := connect.NewUnaryHandler(
		OrgServiceNestOrgProcedure,
		svc.NestOrg,
		connect.WithSchema(orgServiceMethods.ByName("NestOrg")),
		connect.WithHandlerOptions(opts...),
	)
	orgServiceDefineRoleHandler := connect.NewUnaryHandler(
		OrgServiceDefineRoleProcedure,
		svc.DefineRole,
		connect.WithSchema(orgServiceMethods.ByName("DefineRole")),
		connect.WithHandlerOptions(opts...),
	)
	orgServiceAssignRoleHandler := connect.NewUnaryHandler(
		OrgServiceAssignRoleProcedure,
		svc.AssignRole,
		connect.WithSchema(orgServiceMethods.ByName("AssignRole")),
		connect.WithHandlerOptions(opts...),
	)
	orgServiceInviteUserHandler := connect.NewUnaryHandler(
		OrgServiceInviteUserProcedure,
		svc.InviteUser,
		connect.WithSchema(orgServiceMethods.ByName("InviteUser")),
		connect.WithHandlerOptions(opts...),
	)
	return "/rootstock.v1.OrgService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case OrgServiceCreateOrgProcedure:
			orgServiceCreateOrgHandler.ServeHTTP(w, r)
		case OrgServiceNestOrgProcedure:
			orgServiceNestOrgHandler.ServeHTTP(w, r)
		case OrgServiceDefineRoleProcedure:
			orgServiceDefineRoleHandler.ServeHTTP(w, r)
		case OrgServiceAssignRoleProcedure:
			orgServiceAssignRoleHandler.ServeHTTP(w, r)
		case OrgServiceInviteUserProcedure:
			orgServiceInviteUserHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedOrgServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedOrgServiceHandler struct{}

func (UnimplementedOrgServiceHandler) CreateOrg(context.Context, *connect.Request[v1.CreateOrgRequest]) (*connect.Response[v1.CreateOrgResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rootstock.v1.OrgService.CreateOrg is not implemented"))
}

func (UnimplementedOrgServiceHandler) NestOrg(context.Context, *connect.Request[v1.NestOrgRequest]) (*connect.Response[v1.NestOrgResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rootstock.v1.OrgService.NestOrg is not implemented"))
}

func (UnimplementedOrgServiceHandler) DefineRole(context.Context, *connect.Request[v1.DefineRoleRequest]) (*connect.Response[v1.DefineRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rootstock.v1.OrgService.DefineRole is not implemented"))
}

func (UnimplementedOrgServiceHandler) AssignRole(context.Context, *connect.Request[v1.AssignRoleRequest]) (*connect.Response[v1.AssignRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rootstock.v1.OrgService.AssignRole is not implemented"))
}

func (UnimplementedOrgServiceHandler) InviteUser(context.Context, *connect.Request[v1.InviteUserRequest]) (*connect.Response[v1.InviteUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rootstock.v1.OrgService.InviteUser is not implemented"))
}

// ScoreServiceClient is a client for the rootstock.v1.ScoreService service.
type ScoreServiceClient interface {
	GetContribution(context.Context, *connect.Request[v1.GetContributionRequest]) (*connect.Response[v1.GetContributionResponse], error)
}

// NewScoreServiceClient constructs a client for the rootstock.v1.ScoreService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewScoreServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ScoreServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	scoreServiceMethods := v1.File_rootstock_v1_rootstock_proto.Services().ByName("ScoreService").Methods()
	return &scoreServiceClient{
		getContribution: connect.NewClient[v1.GetContributionRequest, v1.GetContributionResponse](
			httpClient,
			baseURL+ScoreServiceGetContributionProcedure,
			connect.WithSchema(scoreServiceMethods.ByName("GetContribution")),
			connect.WithClientOptions(opts...),
		),
	}
}

// scoreServiceClient implements ScoreServiceClient.
type scoreServiceClient struct {
	getContribution *connect.Client[v1.GetContributionRequest, v1.GetContributionResponse]
}

// GetContribution calls rootstock.v1.ScoreService.GetContribution.
func (c *scoreServiceClient) GetContribution(ctx context.Context, req *connect.Request[v1.GetContributionRequest]) (*connect.Response[v1.GetContributionResponse], error) {
	return c.getContribution.CallUnary(ctx, req)
}

// ScoreServiceHandler is an implementation of the rootstock.v1.ScoreService service.
type ScoreServiceHandler interface {
	GetContribution(context.Context, *connect.Request[v1.GetContributionRequest]) (*connect.Response[v1.GetContributionResponse], error)
}

// NewScoreServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewScoreServiceHandler(svc ScoreServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	scoreServiceMethods := v1.File_rootstock_v1_rootstock_proto.Services().ByName("ScoreService").Methods()
	scoreServiceGetContributionHandler := connect.NewUnaryHandler(
		ScoreServiceGetContributionProcedure,
		svc.GetContribution,
		connect.WithSchema(scoreServiceMethods.ByName("GetContribution")),
		connect.WithHandlerOptions(opts...),
	)
	return "/rootstock.v1.ScoreService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ScoreServiceGetContributionProcedure:
			scoreServiceGetContributionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedScoreServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedScoreServiceHandler struct{}

func (UnimplementedScoreServiceHandler) GetContribution(context.Context, *connect.Request[v1.GetContributionRequest]) (*connect.Response[v1.GetContributionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rootstock.v1.ScoreService.GetContribution is not implemented"))
}

// DeviceServiceClient is a client for the rootstock.v1.DeviceService service.
type DeviceServiceClient interface {
	GetDevice(context.Context, *connect.Request[v1.GetDeviceRequest]) (*connect.Response[v1.GetDeviceResponse], error)
	RevokeDevice(context.Context, *connect.Request[v1.RevokeDeviceRequest]) (*connect.Response[v1.RevokeDeviceResponse], error)
	ReinstateDevice(context.Context, *connect.Request[v1.ReinstateDeviceRequest]) (*connect.Response[v1.ReinstateDeviceResponse], error)
	EnrollInCampaign(context.Context, *connect.Request[v1.EnrollInCampaignRequest]) (*connect.Response[v1.EnrollInCampaignResponse], error)
}

// NewDeviceServiceClient constructs a client for the rootstock.v1.DeviceService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDeviceServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DeviceServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	deviceServiceMethods := v1.File_rootstock_v1_rootstock_proto.Services().ByName("DeviceService").Methods()
	return &deviceServiceClient{
		getDevice: connect.NewClient[v1.GetDeviceRequest, v1.GetDeviceResponse](
			httpClient,
			baseURL+DeviceServiceGetDeviceProcedure,
			connect.WithSchema(deviceServiceMethods.ByName("GetDevice")),
			connect.WithClientOptions(opts...),
		),
		revokeDevice: connect.NewClient[v1.RevokeDeviceRequest, v1.RevokeDeviceResponse](
			httpClient,
			baseURL+DeviceServiceRevokeDeviceProcedure,
			connect.WithSchema(deviceServiceMethods.ByName("RevokeDevice")),
			connect.WithClientOptions(opts...),
		),
		reinstateDevice: connect.NewClient[v1.ReinstateDeviceRequest, v1.ReinstateDeviceResponse](
			httpClient,
			baseURL+DeviceServiceReinstateDeviceProcedure,
			connect.WithSchema(deviceServiceMethods.ByName("ReinstateDevice")),
			connect.WithClientOptions(opts...),
		),
		enrollInCampaign: connect.NewClient[v1.EnrollInCampaignRequest, v1.EnrollInCampaignResponse](
			httpClient,
			baseURL+DeviceServiceEnrollInCampaignProcedure,
			connect.WithSchema(deviceServiceMethods.ByName("EnrollInCampaign")),
			connect.WithClientOptions(opts...),
		),
	}
}

// deviceServiceClient implements DeviceServiceClient.
type deviceServiceClient struct {
	getDevice        *connect.Client[v1.GetDeviceRequest, v1.GetDeviceResponse]
	revokeDevice     *connect.Client[v1.RevokeDeviceRequest, v1.RevokeDeviceResponse]
	reinstateDevice  *connect.Client[v1.ReinstateDeviceRequest, v1.ReinstateDeviceResponse]
	enrollInCampaign *connect.Client[v1.EnrollInCampaignRequest, v1.EnrollInCampaignResponse]
}

// GetDevice calls rootstock.v1.DeviceService.GetDevice.
func (c *deviceServiceClient) GetDevice(ctx context.Context, req *connect.Request[v1.GetDeviceRequest]) (*connect.Response[v1.GetDeviceResponse], error) {
	return c.getDevice.CallUnary(ctx, req)
}

// RevokeDevice calls rootstock.v1.DeviceService.RevokeDevice.
func (c *deviceServiceClient) RevokeDevice(ctx context.Context, req *connect.Request[v1.RevokeDeviceRequest]) (*connect.Response[v1.RevokeDeviceResponse], error) {
	return c.revokeDevice.CallUnary(ctx, req)
}

// ReinstateDevice calls rootstock.v1.DeviceService.ReinstateDevice.
func (c *deviceServiceClient) ReinstateDevice(ctx context.Context, req *connect.Request[v1.ReinstateDeviceRequest]) (*connect.Response[v1.ReinstateDeviceResponse], error) {
	return c.reinstateDevice.CallUnary(ctx, req)
}

// EnrollInCampaign calls rootstock.v1.DeviceService.EnrollInCampaign.
func (c *deviceServiceClient) EnrollInCampaign(ctx context.Context, req *connect.Request[v1.EnrollInCampaignRequest]) (*connect.Response[v1.EnrollInCampaignResponse], error) {
	return c.enrollInCampaign.CallUnary(ctx, req)
}

// DeviceServiceHandler is an implementation of the rootstock.v1.DeviceService service.
type DeviceServiceHandler interface {
	GetDevice(context.Context, *connect.Request[v1.GetDeviceRequest]) (*connect.Response[v1.GetDeviceResponse], error)
	RevokeDevice(context.Context, *connect.Request[v1.RevokeDeviceRequest]) (*connect.Response[v1.RevokeDeviceResponse], error)
	ReinstateDevice(context.Context, *connect.Request[v1.ReinstateDeviceRequest]) (*connect.Response[v1.ReinstateDeviceResponse], error)
	EnrollInCampaign(context.Context, *connect.Request[v1.EnrollInCampaignRequest]) (*connect.Response[v1.EnrollInCampaignResponse], error)
}

// NewDeviceServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDeviceServiceHandler(svc DeviceServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	deviceServiceMethods := v1.File_rootstock_v1_rootstock_proto.Services().ByName("DeviceService").Methods()
	deviceServiceGetDeviceHandler := connect.NewUnaryHandler(
		DeviceServiceGetDeviceProcedure,
		svc.GetDevice,
		connect.WithSchema(deviceServiceMethods.ByName("GetDevice")),
		connect.WithHandlerOptions(opts...),
	)
	deviceServiceRevokeDeviceHandler := connect.NewUnaryHandler(
		DeviceServiceRevokeDeviceProcedure,
		svc.RevokeDevice,
		connect.WithSchema(deviceServiceMethods.ByName("RevokeDevice")),
		connect.WithHandlerOptions(opts...),
	)
	deviceServiceReinstateDeviceHandler := connect.NewUnaryHandler(
		DeviceServiceReinstateDeviceProcedure,
		svc.ReinstateDevice,
		connect.WithSchema(deviceServiceMethods.ByName("ReinstateDevice")),
		connect.WithHandlerOptions(opts...),
	)
	deviceServiceEnrollInCampaignHandler := connect.NewUnaryHandler(
		DeviceServiceEnrollInCampaignProcedure,
		svc.EnrollInCampaign,
		connect.WithSchema(deviceServiceMethods.ByName("EnrollInCampaign")),
		connect.WithHandlerOptions(opts...),
	)
	return "/rootstock.v1.DeviceService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DeviceServiceGetDeviceProcedure:
			deviceServiceGetDeviceHandler.ServeHTTP(w, r)
		case DeviceServiceRevokeDeviceProcedure:
			deviceServiceRevokeDeviceHandler.ServeHTTP(w, r)
		case DeviceServiceReinstateDeviceProcedure:
			deviceServiceReinstateDeviceHandler.ServeHTTP(w, r)
		case DeviceServiceEnrollInCampaignProcedure:
			deviceServiceEnrollInCampaignHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDeviceServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDeviceServiceHandler struct{}

func (UnimplementedDeviceServiceHandler) GetDevice(context.Context, *connect.Request[v1.GetDeviceRequest]) (*connect.Response[v1.GetDeviceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rootstock.v1.DeviceService.GetDevice is not implemented"))
}

func (UnimplementedDeviceServiceHandler) RevokeDevice(context.Context, *connect.Request[v1.RevokeDeviceRequest]) (*connect.Response[v1.RevokeDeviceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rootstock.v1.DeviceService.RevokeDevice is not implemented"))
}

func (UnimplementedDeviceServiceHandler) ReinstateDevice(context.Context, *connect.Request[v1.ReinstateDeviceRequest]) (*connect.Response[v1.ReinstateDeviceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rootstock.v1.DeviceService.ReinstateDevice is not implemented"))
}

func (UnimplementedDeviceServiceHandler) EnrollInCampaign(context.Context, *connect.Request[v1.EnrollInCampaignRequest]) (*connect.Response[v1.EnrollInCampaignResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rootstock.v1.DeviceService.EnrollInCampaign is not implemented"))
}

// UserServiceClient is a client for the rootstock.v1.UserService service.
type UserServiceClient interface {
	RegisterUser(context.Context, *connect.Request[v1.RegisterUserRequest]) (*connect.Response[v1.RegisterUserResponse], error)
	GetMe(context.Context, *connect.Request[v1.GetMeRequest]) (*connect.Response[v1.GetMeResponse], error)
	Login(context.Context, *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error)
	Logout(context.Context, *connect.Request[v1.LogoutRequest]) (*connect.Response[v1.LogoutResponse], error)
	RegisterResearcher(context.Context, *connect.Request[v1.RegisterResearcherRequest]) (*connect.Response[v1.RegisterResearcherResponse], error)
	VerifyEmail(context.Context, *connect.Request[v1.VerifyEmailRequest]) (*connect.Response[v1.VerifyEmailResponse], error)
}

// NewUserServiceClient constructs a client for the rootstock.v1.UserService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUserServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UserServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	userServiceMethods := v1.File_rootstock_v1_rootstock_proto.Services().ByName("UserService").Methods()
	return &userServiceClient{
		registerUser: connect.NewClient[v1.RegisterUserRequest, v1.RegisterUserResponse](
			httpClient,
			baseURL+UserServiceRegisterUserProcedure,
			connect.WithSchema(userServiceMethods.ByName("RegisterUser")),
			connect.WithClientOptions(opts...),
		),
		getMe: connect.NewClient[v1.GetMeRequest, v1.GetMeResponse](
			httpClient,
			baseURL+UserServiceGetMeProcedure,
			connect.WithSchema(userServiceMethods.ByName("GetMe")),
			connect.WithClientOptions(opts...),
		),
		login: connect.NewClient[v1.LoginRequest, v1.LoginResponse](
			httpClient,
			baseURL+UserServiceLoginProcedure,
			connect.WithSchema(userServiceMethods.ByName("Login")),
			connect.WithClientOptions(opts...),
		),
		logout: connect.NewClient[v1.LogoutRequest, v1.LogoutResponse](
			httpClient,
			baseURL+UserServiceLogoutProcedure,
			connect.WithSchema(userServiceMethods.ByName("Logout")),
			connect.WithClientOptions(opts...),
		),
		registerResearcher: connect.NewClient[v1.RegisterResearcherRequest, v1.RegisterResearcherResponse](
			httpClient,
			baseURL+UserServiceRegisterResearcherProcedure,
			connect.WithSchema(userServiceMethods.ByName("RegisterResearcher")),
			connect.WithClientOptions(opts...),
		),
		verifyEmail: connect.NewClient[v1.VerifyEmailRequest, v1.VerifyEmailResponse](
			httpClient,
			baseURL+UserServiceVerifyEmailProcedure,
			connect.WithSchema(userServiceMethods.ByName("VerifyEmail")),
			connect.WithClientOptions(opts...),
		),
	}
}

// userServiceClient implements UserServiceClient.
type userServiceClient struct {
	registerUser       *connect.Client[v1.RegisterUserRequest, v1.RegisterUserResponse]
	getMe              *connect.Client[v1.GetMeRequest, v1.GetMeResponse]
	login              *connect.Client[v1.LoginRequest, v1.LoginResponse]
	logout             *connect.Client[v1.LogoutRequest, v1.LogoutResponse]
	registerResearcher *connect.Client[v1.RegisterResearcherRequest, v1.RegisterResearcherResponse]
	verifyEmail        *connect.Client[v1.VerifyEmailRequest, v1.VerifyEmailResponse]
}

// RegisterUser calls rootstock.v1.UserService.RegisterUser.
func (c *userServiceClient) RegisterUser(ctx context.Context, req *connect.Request[v1.RegisterUserRequest]) (*connect.Response[v1.RegisterUserResponse], error) {
	return c.registerUser.CallUnary(ctx, req)
}

// GetMe calls rootstock.v1.UserService.GetMe.
func (c *userServiceClient) GetMe(ctx context.Context, req *connect.Request[v1.GetMeRequest]) (*connect.Response[v1.GetMeResponse], error) {
	return c.getMe.CallUnary(ctx, req)
}

// Login calls rootstock.v1.UserService.Login.
func (c *userServiceClient) Login(ctx context.Context, req *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error) {
	return c.login.CallUnary(ctx, req)
}

// Logout calls rootstock.v1.UserService.Logout.
func (c *userServiceClient) Logout(ctx context.Context, req *connect.Request[v1.LogoutRequest]) (*connect.Response[v1.LogoutResponse], error) {
	return c.logout.CallUnary(ctx, req)
}

// RegisterResearcher calls rootstock.v1.UserService.RegisterResearcher.
func (c *userServiceClient) RegisterResearcher(ctx context.Context, req *connect.Request[v1.RegisterResearcherRequest]) (*connect.Response[v1.RegisterResearcherResponse], error) {
	return c.registerResearcher.CallUnary(ctx, req)
}

// VerifyEmail calls rootstock.v1.UserService.VerifyEmail.
func (c *userServiceClient) VerifyEmail(ctx context.Context, req *connect.Request[v1.VerifyEmailRequest]) (*connect.Response[v1.VerifyEmailResponse], error) {
	return c.verifyEmail.CallUnary(ctx, req)
}

// UserServiceHandler is an implementation of the rootstock.v1.UserService service.
type UserServiceHandler interface {
	RegisterUser(context.Context, *connect.Request[v1.RegisterUserRequest]) (*connect.Response[v1.RegisterUserResponse], error)
	GetMe(context.Context, *connect.Request[v1.GetMeRequest]) (*connect.Response[v1.GetMeResponse], error)
	Login(context.Context, *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error)
	Logout(context.Context, *connect.Request[v1.LogoutRequest]) (*connect.Response[v1.LogoutResponse], error)
	RegisterResearcher(context.Context, *connect.Request[v1.RegisterResearcherRequest]) (*connect.Response[v1.RegisterResearcherResponse], error)
	VerifyEmail(context.Context, *connect.Request[v1.VerifyEmailRequest]) (*connect.Response[v1.VerifyEmailResponse], error)
}

// NewUserServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUserServiceHandler(svc UserServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	userServiceMethods := v1.File_rootstock_v1_rootstock_proto.Services().ByName("UserService").Methods()
	userServiceRegisterUserHandler := connect.NewUnaryHandler(
		UserServiceRegisterUserProcedure,
		svc.RegisterUser,
		connect.WithSchema(userServiceMethods.ByName("RegisterUser")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceGetMeHandler := connect.NewUnaryHandler(
		UserServiceGetMeProcedure,
		svc.GetMe,
		connect.WithSchema(userServiceMethods.ByName("GetMe")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceLoginHandler := connect.NewUnaryHandler(
		UserServiceLoginProcedure,
		svc.Login,
		connect.WithSchema(userServiceMethods.ByName("Login")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceLogoutHandler := connect.NewUnaryHandler(
		UserServiceLogoutProcedure,
		svc.Logout,
		connect.WithSchema(userServiceMethods.ByName("Logout")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceRegisterResearcherHandler := connect.NewUnaryHandler(
		UserServiceRegisterResearcherProcedure,
		svc.RegisterResearcher,
		connect.WithSchema(userServiceMethods.ByName("RegisterResearcher")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceVerifyEmailHandler := connect.NewUnaryHandler(
		UserServiceVerifyEmailProcedure,
		svc.VerifyEmail,
		connect.WithSchema(userServiceMethods.ByName("VerifyEmail")),
		connect.WithHandlerOptions(opts...),
	)
	return "/rootstock.v1.UserService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UserServiceRegisterUserProcedure:
			userServiceRegisterUserHandler.ServeHTTP(w, r)
		case UserServiceGetMeProcedure:
			userServiceGetMeHandler.ServeHTTP(w, r)
		case UserServiceLoginProcedure:
			userServiceLoginHandler.ServeHTTP(w, r)
		case UserServiceLogoutProcedure:
			userServiceLogoutHandler.ServeHTTP(w, r)
		case UserServiceRegisterResearcherProcedure:
			userServiceRegisterResearcherHandler.ServeHTTP(w, r)
		case UserServiceVerifyEmailProcedure:
			userServiceVerifyEmailHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUserServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedUserServiceHandler struct{}

func (UnimplementedUserServiceHandler) RegisterUser(context.Context, *connect.Request[v1.RegisterUserRequest]) (*connect.Response[v1.RegisterUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rootstock.v1.UserService.RegisterUser is not implemented"))
}

func (UnimplementedUserServiceHandler) GetMe(context.Context, *connect.Request[v1.GetMeRequest]) (*connect.Response[v1.GetMeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rootstock.v1.UserService.GetMe is not implemented"))
}

func (UnimplementedUserServiceHandler) Login(context.Context, *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rootstock.v1.UserService.Login is not implemented"))
}

func (UnimplementedUserServiceHandler) Logout(context.Context, *connect.Request[v1.LogoutRequest]) (*connect.Response[v1.LogoutResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rootstock.v1.UserService.Logout is not implemented"))
}

func (UnimplementedUserServiceHandler) RegisterResearcher(context.Context, *connect.Request[v1.RegisterResearcherRequest]) (*connect.Response[v1.RegisterResearcherResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rootstock.v1.UserService.RegisterResearcher is not implemented"))
}

func (UnimplementedUserServiceHandler) VerifyEmail(context.Context, *connect.Request[v1.VerifyEmailRequest]) (*connect.Response[v1.VerifyEmailResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rootstock.v1.UserService.VerifyEmail is not implemented"))
}

// ScitizenServiceClient is a client for the rootstock.v1.ScitizenService service.
type ScitizenServiceClient interface {
	RegisterScitizen(context.Context, *connect.Request[v1.RegisterScitizenRequest]) (*connect.Response[v1.RegisterScitizenResponse], error)
	GetDashboard(context.Context, *connect.Request[v1.GetDashboardRequest]) (*connect.Response[v1.GetDashboardResponse], error)
	BrowsePublishedCampaigns(context.Context, *connect.Request[v1.BrowsePublishedCampaignsRequest]) (*connect.Response[v1.BrowsePublishedCampaignsResponse], error)
	GetCampaignDetail(context.Context, *connect.Request[v1.GetCampaignDetailRequest]) (*connect.Response[v1.GetCampaignDetailResponse], error)
	SearchCampaigns(context.Context, *connect.Request[v1.SearchCampaignsRequest]) (*connect.Response[v1.SearchCampaignsResponse], error)
	EnrollDevice(context.Context, *connect.Request[v1.EnrollDeviceRequest]) (*connect.Response[v1.EnrollDeviceResponse], error)
	WithdrawEnrollment(context.Context, *connect.Request[v1.WithdrawEnrollmentRequest]) (*connect.Response[v1.WithdrawEnrollmentResponse], error)
	GetDevices(context.Context, *connect.Request[v1.GetDevicesRequest]) (*connect.Response[v1.GetDevicesResponse], error)
	GetDeviceDetail(context.Context, *connect.Request[v1.GetDeviceDetailRequest]) (*connect.Response[v1.GetDeviceDetailResponse], error)
	GetNotifications(context.Context, *connect.Request[v1.GetNotificationsRequest]) (*connect.Response[v1.GetNotificationsResponse], error)
	GetContributions(context.Context, *connect.Request[v1.GetContributionsRequest]) (*connect.Response[v1.GetContributionsResponse], error)
	GetOnboardingState(context.Context, *connect.Request[v1.GetOnboardingStateRequest]) (*connect.Response[v1.GetOnboardingStateResponse], error)
}

// NewScitizenServiceClient constructs a client for the rootstock.v1.ScitizenService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewScitizenServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ScitizenServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	scitizenServiceMethods := v1.File_rootstock_v1_rootstock_proto.Services().ByName("ScitizenService").Methods()
	return &scitizenServiceClient{
		registerScitizen: connect.NewClient[v1.RegisterScitizenRequest, v1.RegisterScitizenResponse](
			httpClient,
			baseURL+ScitizenServiceRegisterScitizenProcedure,
			connect.WithSchema(scitizenServiceMethods.ByName("RegisterScitizen")),
			connect.WithClientOptions(opts...),
		),
		getDashboard: connect.NewClient[v1.GetDashboardRequest, v1.GetDashboardResponse](
			httpClient,
			baseURL+ScitizenServiceGetDashboardProcedure,
			connect.WithSchema(scitizenServiceMethods.ByName("GetDashboard")),
			connect.WithClientOptions(opts...),
		),
		browsePublishedCampaigns: connect.NewClient[v1.BrowsePublishedCampaignsRequest, v1.BrowsePublishedCampaignsResponse](
			httpClient,
			baseURL+ScitizenServiceBrowsePublishedCampaignsProcedure,
			connect.WithSchema(scitizenServiceMethods.ByName("BrowsePublishedCampaigns")),
			connect.WithClientOptions(opts...),
		),
		getCampaignDetail: connect.NewClient[v1.GetCampaignDetailRequest, v1.GetCampaignDetailResponse](
			httpClient,
			baseURL+ScitizenServiceGetCampaignDetailProcedure,
			connect.WithSchema(scitizenServiceMethods.ByName("GetCampaignDetail")),
			connect.WithClientOptions(opts...),
		),
		searchCampaigns: connect.NewClient[v1.SearchCampaignsRequest, v1.SearchCampaignsResponse](
			httpClient,
			baseURL+ScitizenServiceSearchCampaignsProcedure,
			connect.WithSchema(scitizenServiceMethods.ByName("SearchCampaigns")),
			connect.WithClientOptions(opts...),
		),
		enrollDevice: connect.NewClient[v1.EnrollDeviceRequest, v1.EnrollDeviceResponse](
			httpClient,
			baseURL+ScitizenServiceEnrollDeviceProcedure,
			connect.WithSchema(scitizenServiceMethods.ByName("EnrollDevice")),
			connect.WithClientOptions(opts...),
		),
		withdrawEnrollment: connect.NewClient[v1.WithdrawEnrollmentRequest, v1.WithdrawEnrollmentResponse](
			httpClient,
			baseURL+ScitizenServiceWithdrawEnrollmentProcedure,
			connect.WithSchema(scitizenServiceMethods.ByName("WithdrawEnrollment")),
			connect.WithClientOptions(opts...),
		),
		getDevices: connect.NewClient[v1.GetDevicesRequest, v1.GetDevicesResponse](
			httpClient,
			baseURL+ScitizenServiceGetDevicesProcedure,
			connect.WithSchema(scitizenServiceMethods.ByName("GetDevices")),
			connect.WithClientOptions(opts...),
		),
		getDeviceDetail: connect.NewClient[v1.GetDeviceDetailRequest, v1.GetDeviceDetailResponse](
			httpClient,
			baseURL+ScitizenServiceGetDeviceDetailProcedure,
			connect.WithSchema(scitizenServiceMethods.ByName("GetDeviceDetail")),
			connect.WithClientOptions(opts...),
		),
		getNotifications: connect.NewClient[v1.GetNotificationsRequest, v1.GetNotificationsResponse](
			httpClient,
			baseURL+ScitizenServiceGetNotificationsProcedure,
			connect.WithSchema(scitizenServiceMethods.ByName("GetNotifications")),
			connect.WithClientOptions(opts...),
		),
		getContributions: connect.NewClient[v1.GetContributionsRequest, v1.GetContributionsResponse](
			httpClient,
			baseURL+ScitizenServiceGetContributionsProcedure,
			connect.WithSchema(scitizenServiceMethods.ByName("GetContributions")),
			connect.WithClientOptions(opts...),
		),
		getOnboardingState: connect.NewClient[v1.GetOnboardingStateRequest, v1.GetOnboardingStateResponse](
			httpClient,
			baseURL+ScitizenServiceGetOnboardingStateProcedure,
			connect.WithSchema(scitizenServiceMethods.ByName("GetOnboardingState")),
			connect.WithClientOptions(opts...),
		),
	}
}

// scitizenServiceClient implements ScitizenServiceClient.
type scitizenServiceClient struct {
	registerScitizen         *connect.Client[v1.RegisterScitizenRequest, v1.RegisterScitizenResponse]
	getDashboard             *connect.Client[v1.GetDashboardRequest, v1.GetDashboardResponse]
	browsePublishedCampaigns *connect.Client[v1.BrowsePublishedCampaignsRequest, v1.BrowsePublishedCampaignsResponse]
	getCampaignDetail        *connect.Client[v1.GetCampaignDetailRequest, v1.GetCampaignDetailResponse]
	searchCampaigns          *connect.Client[v1.SearchCampaignsRequest, v1.SearchCampaignsResponse]
	enrollDevice             *connect.Client[v1.EnrollDeviceRequest, v1.EnrollDeviceResponse]
	withdrawEnrollment       *connect.Client[v1.WithdrawEnrollmentRequest, v1.WithdrawEnrollmentResponse]
	getDevices               *connect.Client[v1.GetDevicesRequest, v1.GetDevicesResponse]
	getDeviceDetail          *connect.Client[v1.GetDeviceDetailRequest, v1.GetDeviceDetailResponse]
	getNotifications         *connect.Client[v1.GetNotificationsRequest, v1.GetNotificationsResponse]
	getContributions         *connect.Client[v1.GetContributionsRequest, v1.GetContributionsResponse]
	getOnboardingState       *connect.Client[v1.GetOnboardingStateRequest, v1.GetOnboardingStateResponse]
}

// RegisterScitizen calls rootstock.v1.ScitizenService.RegisterScitizen.
func (c *scitizenServiceClient) RegisterScitizen(ctx context.Context, req *connect.Request[v1.RegisterScitizenRequest]) (*connect.Response[v1.RegisterScitizenResponse], error) {
	return c.registerScitizen.CallUnary(ctx, req)
}

// GetDashboard calls rootstock.v1.ScitizenService.GetDashboard.
func (c *scitizenServiceClient) GetDashboard(ctx context.Context, req *connect.Request[v1.GetDashboardRequest]) (*connect.Response[v1.GetDashboardResponse], error) {
	return c.getDashboard.CallUnary(ctx, req)
}

// BrowsePublishedCampaigns calls rootstock.v1.ScitizenService.BrowsePublishedCampaigns.
func (c *scitizenServiceClient) BrowsePublishedCampaigns(ctx context.Context, req *connect.Request[v1.BrowsePublishedCampaignsRequest]) (*connect.Response[v1.BrowsePublishedCampaignsResponse], error) {
	return c.browsePublishedCampaigns.CallUnary(ctx, req)
}

// GetCampaignDetail calls rootstock.v1.ScitizenService.GetCampaignDetail.
func (c *scitizenServiceClient) GetCampaignDetail(ctx context.Context, req *connect.Request[v1.GetCampaignDetailRequest]) (*connect.Response[v1.GetCampaignDetailResponse], error) {
	return c.getCampaignDetail.CallUnary(ctx, req)
}

// SearchCampaigns calls rootstock.v1.ScitizenService.SearchCampaigns.
func (c *scitizenServiceClient) SearchCampaigns(ctx context.Context, req *connect.Request[v1.SearchCampaignsRequest]) (*connect.Response[v1.SearchCampaignsResponse], error) {
	return c.searchCampaigns.CallUnary(ctx, req)
}

// EnrollDevice calls rootstock.v1.ScitizenService.EnrollDevice.
func (c *scitizenServiceClient) EnrollDevice(ctx context.Context, req *connect.Request[v1.EnrollDeviceRequest]) (*connect.Response[v1.EnrollDeviceResponse], error) {
	return c.enrollDevice.CallUnary(ctx, req)
}

// WithdrawEnrollment calls rootstock.v1.ScitizenService.WithdrawEnrollment.
func (c *scitizenServiceClient) WithdrawEnrollment(ctx context.Context, req *connect.Request[v1.WithdrawEnrollmentRequest]) (*connect.Response[v1.WithdrawEnrollmentResponse], error) {
	return c.withdrawEnrollment.CallUnary(ctx, req)
}

// GetDevices calls rootstock.v1.ScitizenService.GetDevices.
func (c *scitizenServiceClient) GetDevices(ctx context.Context, req *connect.Request[v1.GetDevicesRequest]) (*connect.Response[v1.GetDevicesResponse], error) {
	return c.getDevices.CallUnary(ctx, req)
}

// GetDeviceDetail calls rootstock.v1.ScitizenService.GetDeviceDetail.
func (c *scitizenServiceClient) GetDeviceDetail(ctx context.Context, req *connect.Request[v1.GetDeviceDetailRequest]) (*connect.Response[v1.GetDeviceDetailResponse], error) {
	return c.getDeviceDetail.CallUnary(ctx, req)
}

// GetNotifications calls rootstock.v1.ScitizenService.GetNotifications.
func (c *scitizenServiceClient) GetNotifications(ctx context.Context, req *connect.Request[v1.GetNotificationsRequest]) (*connect.Response[v1.GetNotificationsResponse], error) {
	return c.getNotifications.CallUnary(ctx, req)
}

// GetContributions calls rootstock.v1.ScitizenService.GetContributions.
func (c *scitizenServiceClient) GetContributions(ctx context.Context, req *connect.Request[v1.GetContributionsRequest]) (*connect.Response[v1.GetContributionsResponse], error) {
	return c.getContributions.CallUnary(ctx, req)
}

// GetOnboardingState calls rootstock.v1.ScitizenService.GetOnboardingState.
func (c *scitizenServiceClient) GetOnboardingState(ctx context.Context, req *connect.Request[v1.GetOnboardingStateRequest]) (*connect.Response[v1.GetOnboardingStateResponse], error) {
	return c.getOnboardingState.CallUnary(ctx, req)
}

// ScitizenServiceHandler is an implementation of the rootstock.v1.ScitizenService service.
type ScitizenServiceHandler interface {
	RegisterScitizen(context.Context, *connect.Request[v1.RegisterScitizenRequest]) (*connect.Response[v1.RegisterScitizenResponse], error)
	GetDashboard(context.Context, *connect.Request[v1.GetDashboardRequest]) (*connect.Response[v1.GetDashboardResponse], error)
	BrowsePublishedCampaigns(context.Context, *connect.Request[v1.BrowsePublishedCampaignsRequest]) (*connect.Response[v1.BrowsePublishedCampaignsResponse], error)
	GetCampaignDetail(context.Context, *connect.Request[v1.GetCampaignDetailRequest]) (*connect.Response[v1.GetCampaignDetailResponse], error)
	SearchCampaigns(context.Context, *connect.Request[v1.SearchCampaignsRequest]) (*connect.Response[v1.SearchCampaignsResponse], error)
	EnrollDevice(context.Context, *connect.Request[v1.EnrollDeviceRequest]) (*connect.Response[v1.EnrollDeviceResponse], error)
	WithdrawEnrollment(context.Context, *connect.Request[v1.WithdrawEnrollmentRequest]) (*connect.Response[v1.WithdrawEnrollmentResponse], error)
	GetDevices(context.Context, *connect.Request[v1.GetDevicesRequest]) (*connect.Response[v1.GetDevicesResponse], error)
	GetDeviceDetail(context.Context, *connect.Request[v1.GetDeviceDetailRequest]) (*connect.Response[v1.GetDeviceDetailResponse], error)
	GetNotifications(context.Context, *connect.Request[v1.GetNotificationsRequest]) (*connect.Response[v1.GetNotificationsResponse], error)
	GetContributions(context.Context, *connect.Request[v1.GetContributionsRequest]) (*connect.Response[v1.GetContributionsResponse], error)
	GetOnboardingState(context.Context, *connect.Request[v1.GetOnboardingStateRequest]) (*connect.Response[v1.GetOnboardingStateResponse], error)
}

// NewScitizenServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewScitizenServiceHandler(svc ScitizenServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	scitizenServiceMethods := v1.File_rootstock_v1_rootstock_proto.Services().ByName("ScitizenService").Methods()
	scitizenServiceRegisterScitizenHandler := connect.NewUnaryHandler(
		ScitizenServiceRegisterScitizenProcedure,
		svc.RegisterScitizen,
		connect.WithSchema(scitizenServiceMethods.ByName("RegisterScitizen")),
		connect.WithHandlerOptions(opts...),
	)
	scitizenServiceGetDashboardHandler := connect.NewUnaryHandler(
		ScitizenServiceGetDashboardProcedure,
		svc.GetDashboard,
		connect.WithSchema(scitizenServiceMethods.ByName("GetDashboard")),
		connect.WithHandlerOptions(opts...),
	)
	scitizenServiceBrowsePublishedCampaignsHandler := connect.NewUnaryHandler(
		ScitizenServiceBrowsePublishedCampaignsProcedure,
		svc.BrowsePublishedCampaigns,
		connect.WithSchema(scitizenServiceMethods.ByName("BrowsePublishedCampaigns")),
		connect.WithHandlerOptions(opts...),
	)
	scitizenServiceGetCampaignDetailHandler := connect.NewUnaryHandler(
		ScitizenServiceGetCampaignDetailProcedure,
		svc.GetCampaignDetail,
		connect.WithSchema(scitizenServiceMethods.ByName("GetCampaignDetail")),
		connect.WithHandlerOptions(opts...),
	)
	scitizenServiceSearchCampaignsHandler := connect.NewUnaryHandler(
		ScitizenServiceSearchCampaignsProcedure,
		svc.SearchCampaigns,
		connect.WithSchema(scitizenServiceMethods.ByName("SearchCampaigns")),
		connect.WithHandlerOptions(opts...),
	)
	scitizenServiceEnrollDeviceHandler := connect.NewUnaryHandler(
		ScitizenServiceEnrollDeviceProcedure,
		svc.EnrollDevice,
		connect.WithSchema(scitizenServiceMethods.ByName("EnrollDevice")),
		connect.WithHandlerOptions(opts...),
	)
	scitizenServiceWithdrawEnrollmentHandler := connect.NewUnaryHandler(
		ScitizenServiceWithdrawEnrollmentProcedure,
		svc.WithdrawEnrollment,
		connect.WithSchema(scitizenServiceMethods.ByName("WithdrawEnrollment")),
		connect.WithHandlerOptions(opts...),
	)
	scitizenServiceGetDevicesHandler := connect.NewUnaryHandler(
		ScitizenServiceGetDevicesProcedure,
		svc.GetDevices,
		connect.WithSchema(scitizenServiceMethods.ByName("GetDevices")),
		connect.WithHandlerOptions(opts...),
	)
	scitizenServiceGetDeviceDetailHandler := connect.NewUnaryHandler(
		ScitizenServiceGetDeviceDetailProcedure,
		svc.GetDeviceDetail,
		connect.WithSchema(scitizenServiceMethods.ByName("GetDeviceDetail")),
		connect.WithHandlerOptions(opts...),
	)
	scitizenServiceGetNotificationsHandler := connect.NewUnaryHandler(
		ScitizenServiceGetNotificationsProcedure,
		svc.GetNotifications,
		connect.WithSchema(scitizenServiceMethods.ByName("GetNotifications")),
		connect.WithHandlerOptions(opts...),
	)
	scitizenServiceGetContributionsHandler := connect.NewUnaryHandler(
		ScitizenServiceGetContributionsProcedure,
		svc.GetContributions,
		connect.WithSchema(scitizenServiceMethods.ByName("GetContributions")),
		connect.WithHandlerOptions(opts...),
	)
	scitizenServiceGetOnboardingStateHandler := connect.NewUnaryHandler(
		ScitizenServiceGetOnboardingStateProcedure,
		svc.GetOnboardingState,
		connect.WithSchema(scitizenServiceMethods.ByName("GetOnboardingState")),
		connect.WithHandlerOptions(opts...),
	)
	return "/rootstock.v1.ScitizenService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ScitizenServiceRegisterScitizenProcedure:
			scitizenServiceRegisterScitizenHandler.ServeHTTP(w, r)
		case ScitizenServiceGetDashboardProcedure:
			scitizenServiceGetDashboardHandler.ServeHTTP(w, r)
		case ScitizenServiceBrowsePublishedCampaignsProcedure:
			scitizenServiceBrowsePublishedCampaignsHandler.ServeHTTP(w, r)
		case ScitizenServiceGetCampaignDetailProcedure:
			scitizenServiceGetCampaignDetailHandler.ServeHTTP(w, r)
		case ScitizenServiceSearchCampaignsProcedure:
			scitizenServiceSearchCampaignsHandler.ServeHTTP(w, r)
		case ScitizenServiceEnrollDeviceProcedure:
			scitizenServiceEnrollDeviceHandler.ServeHTTP(w, r)
		case ScitizenServiceWithdrawEnrollmentProcedure:
			scitizenServiceWithdrawEnrollmentHandler.ServeHTTP(w, r)
		case ScitizenServiceGetDevicesProcedure:
			scitizenServiceGetDevicesHandler.ServeHTTP(w, r)
		case ScitizenServiceGetDeviceDetailProcedure:
			scitizenServiceGetDeviceDetailHandler.ServeHTTP(w, r)
		case ScitizenServiceGetNotificationsProcedure:
			scitizenServiceGetNotificationsHandler.ServeHTTP(w, r)
		case ScitizenServiceGetContributionsProcedure:
			scitizenServiceGetContributionsHandler.ServeHTTP(w, r)
		case ScitizenServiceGetOnboardingStateProcedure:
			scitizenServiceGetOnboardingStateHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedScitizenServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedScitizenServiceHandler struct{}

func (UnimplementedScitizenServiceHandler) RegisterScitizen(context.Context, *connect.Request[v1.RegisterScitizenRequest]) (*connect.Response[v1.RegisterScitizenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rootstock.v1.ScitizenService.RegisterScitizen is not implemented"))
}

func (UnimplementedScitizenServiceHandler) GetDashboard(context.Context, *connect.Request[v1.GetDashboardRequest]) (*connect.Response[v1.GetDashboardResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rootstock.v1.ScitizenService.GetDashboard is not implemented"))
}

func (UnimplementedScitizenServiceHandler) BrowsePublishedCampaigns(context.Context, *connect.Request[v1.BrowsePublishedCampaignsRequest]) (*connect.Response[v1.BrowsePublishedCampaignsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rootstock.v1.ScitizenService.BrowsePublishedCampaigns is not implemented"))
}

func (UnimplementedScitizenServiceHandler) GetCampaignDetail(context.Context, *connect.Request[v1.GetCampaignDetailRequest]) (*connect.Response[v1.GetCampaignDetailResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rootstock.v1.ScitizenService.GetCampaignDetail is not implemented"))
}

func (UnimplementedScitizenServiceHandler) SearchCampaigns(context.Context, *connect.Request[v1.SearchCampaignsRequest]) (*connect.Response[v1.SearchCampaignsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rootstock.v1.ScitizenService.SearchCampaigns is not implemented"))
}

func (UnimplementedScitizenServiceHandler) EnrollDevice(context.Context, *connect.Request[v1.EnrollDeviceRequest]) (*connect.Response[v1.EnrollDeviceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rootstock.v1.ScitizenService.EnrollDevice is not implemented"))
}

func (UnimplementedScitizenServiceHandler) WithdrawEnrollment(context.Context, *connect.Request[v1.WithdrawEnrollmentRequest]) (*connect.Response[v1.WithdrawEnrollmentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rootstock.v1.ScitizenService.WithdrawEnrollment is not implemented"))
}

func (UnimplementedScitizenServiceHandler) GetDevices(context.Context, *connect.Request[v1.GetDevicesRequest]) (*connect.Response[v1.GetDevicesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rootstock.v1.ScitizenService.GetDevices is not implemented"))
}

func (UnimplementedScitizenServiceHandler) GetDeviceDetail(context.Context, *connect.Request[v1.GetDeviceDetailRequest]) (*connect.Response[v1.GetDeviceDetailResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rootstock.v1.ScitizenService.GetDeviceDetail is not implemented"))
}

func (UnimplementedScitizenServiceHandler) GetNotifications(context.Context, *connect.Request[v1.GetNotificationsRequest]) (*connect.Response[v1.GetNotificationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rootstock.v1.ScitizenService.GetNotifications is not implemented"))
}

func (UnimplementedScitizenServiceHandler) GetContributions(context.Context, *connect.Request[v1.GetContributionsRequest]) (*connect.Response[v1.GetContributionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rootstock.v1.ScitizenService.GetContributions is not implemented"))
}

func (UnimplementedScitizenServiceHandler) GetOnboardingState(context.Context, *connect.Request[v1.GetOnboardingStateRequest]) (*connect.Response[v1.GetOnboardingStateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rootstock.v1.ScitizenService.GetOnboardingState is not implemented"))
}

// NotificationServiceClient is a client for the rootstock.v1.NotificationService service.
type NotificationServiceClient interface {
	ListNotifications(context.Context, *connect.Request[v1.ListNotificationsRequest]) (*connect.Response[v1.ListNotificationsResponse], error)
	MarkRead(context.Context, *connect.Request[v1.MarkReadRequest]) (*connect.Response[v1.MarkReadResponse], error)
	GetPreferences(context.Context, *connect.Request[v1.GetPreferencesRequest]) (*connect.Response[v1.GetPreferencesResponse], error)
	UpdatePreferences(context.Context, *connect.Request[v1.UpdatePreferencesRequest]) (*connect.Response[v1.UpdatePreferencesResponse], error)
}

// NewNotificationServiceClient constructs a client for the rootstock.v1.NotificationService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewNotificationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NotificationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	notificationServiceMethods := v1.File_rootstock_v1_rootstock_proto.Services().ByName("NotificationService").Methods()
	return &notificationServiceClient{
		listNotifications: connect.NewClient[v1.ListNotificationsRequest, v1.ListNotificationsResponse](
			httpClient,
			baseURL+NotificationServiceListNotificationsProcedure,
			connect.WithSchema(notificationServiceMethods.ByName("ListNotifications")),
			connect.WithClientOptions(opts...),
		),
		markRead: connect.NewClient[v1.MarkReadRequest, v1.MarkReadResponse](
			httpClient,
			baseURL+NotificationServiceMarkReadProcedure,
			connect.WithSchema(notificationServiceMethods.ByName("MarkRead")),
			connect.WithClientOptions(opts...),
		),
		getPreferences: connect.NewClient[v1.GetPreferencesRequest, v1.GetPreferencesResponse](
			httpClient,
			baseURL+NotificationServiceGetPreferencesProcedure,
			connect.WithSchema(notificationServiceMethods.ByName("GetPreferences")),
			connect.WithClientOptions(opts...),
		),
		updatePreferences: connect.NewClient[v1.UpdatePreferencesRequest, v1.UpdatePreferencesResponse](
			httpClient,
			baseURL+NotificationServiceUpdatePreferencesProcedure,
			connect.WithSchema(notificationServiceMethods.ByName("UpdatePreferences")),
			connect.WithClientOptions(opts...),
		),
	}
}

// notificationServiceClient implements NotificationServiceClient.
type notificationServiceClient struct {
	listNotifications *connect.Client[v1.ListNotificationsRequest, v1.ListNotificationsResponse]
	markRead          *connect.Client[v1.MarkReadRequest, v1.MarkReadResponse]
	getPreferences    *connect.Client[v1.GetPreferencesRequest, v1.GetPreferencesResponse]
	updatePreferences *connect.Client[v1.UpdatePreferencesRequest, v1.UpdatePreferencesResponse]
}

// ListNotifications calls rootstock.v1.NotificationService.ListNotifications.
func (c *notificationServiceClient) ListNotifications(ctx context.Context, req *connect.Request[v1.ListNotificationsRequest]) (*connect.Response[v1.ListNotificationsResponse], error) {
	return c.listNotifications.CallUnary(ctx, req)
}

// MarkRead calls rootstock.v1.NotificationService.MarkRead.
func (c *notificationServiceClient) MarkRead(ctx context.Context, req *connect.Request[v1.MarkReadRequest]) (*connect.Response[v1.MarkReadResponse], error) {
	return c.markRead.CallUnary(ctx, req)
}

// GetPreferences calls rootstock.v1.NotificationService.GetPreferences.
func (c *notificationServiceClient) GetPreferences(ctx context.Context, req *connect.Request[v1.GetPreferencesRequest]) (*connect.Response[v1.GetPreferencesResponse], error) {
	return c.getPreferences.CallUnary(ctx, req)
}

// UpdatePreferences calls rootstock.v1.NotificationService.UpdatePreferences.
func (c *notificationServiceClient) UpdatePreferences(ctx context.Context, req *connect.Request[v1.UpdatePreferencesRequest]) (*connect.Response[v1.UpdatePreferencesResponse], error) {
	return c.updatePreferences.CallUnary(ctx, req)
}

// NotificationServiceHandler is an implementation of the rootstock.v1.NotificationService service.
type NotificationServiceHandler interface {
	ListNotifications(context.Context, *connect.Request[v1.ListNotificationsRequest]) (*connect.Response[v1.ListNotificationsResponse], error)
	MarkRead(context.Context, *connect.Request[v1.MarkReadRequest]) (*connect.Response[v1.MarkReadResponse], error)
	GetPreferences(context.Context, *connect.Request[v1.GetPreferencesRequest]) (*connect.Response[v1.GetPreferencesResponse], error)
	UpdatePreferences(context.Context, *connect.Request[v1.UpdatePreferencesRequest]) (*connect.Response[v1.UpdatePreferencesResponse], error)
}

// NewNotificationServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewNotificationServiceHandler(svc NotificationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	notificationServiceMethods := v1.File_rootstock_v1_rootstock_proto.Services().ByName("NotificationService").Methods()
	notificationServiceListNotificationsHandler := connect.NewUnaryHandler(
		NotificationServiceListNotificationsProcedure,
		svc.ListNotifications,
		connect.WithSchema(notificationServiceMethods.ByName("ListNotifications")),
		connect.WithHandlerOptions(opts...),
	)
	notificationServiceMarkReadHandler := connect.NewUnaryHandler(
		NotificationServiceMarkReadProcedure,
		svc.MarkRead,
		connect.WithSchema(notificationServiceMethods.ByName("MarkRead")),
		connect.WithHandlerOptions(opts...),
	)
	notificationServiceGetPreferencesHandler := connect.NewUnaryHandler(
		NotificationServiceGetPreferencesProcedure,
		svc.GetPreferences,
		connect.WithSchema(notificationServiceMethods.ByName("GetPreferences")),
		connect.WithHandlerOptions(opts...),
	)
	notificationServiceUpdatePreferencesHandler := connect.NewUnaryHandler(
		NotificationServiceUpdatePreferencesProcedure,
		svc.UpdatePreferences,
		connect.WithSchema(notificationServiceMethods.ByName("UpdatePreferences")),
		connect.WithHandlerOptions(opts...),
	)
	return "/rootstock.v1.NotificationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case NotificationServiceListNotificationsProcedure:
			notificationServiceListNotificationsHandler.ServeHTTP(w, r)
		case NotificationServiceMarkReadProcedure:
			notificationServiceMarkReadHandler.ServeHTTP(w, r)
		case NotificationServiceGetPreferencesProcedure:
			notificationServiceGetPreferencesHandler.ServeHTTP(w, r)
		case NotificationServiceUpdatePreferencesProcedure:
			notificationServiceUpdatePreferencesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedNotificationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedNotificationServiceHandler struct{}

func (UnimplementedNotificationServiceHandler) ListNotifications(context.Context, *connect.Request[v1.ListNotificationsRequest]) (*connect.Response[v1.ListNotificationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rootstock.v1.NotificationService.ListNotifications is not implemented"))
}

func (UnimplementedNotificationServiceHandler) MarkRead(context.Context, *connect.Request[v1.MarkReadRequest]) (*connect.Response[v1.MarkReadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rootstock.v1.NotificationService.MarkRead is not implemented"))
}

func (UnimplementedNotificationServiceHandler) GetPreferences(context.Context, *connect.Request[v1.GetPreferencesRequest]) (*connect.Response[v1.GetPreferencesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rootstock.v1.NotificationService.GetPreferences is not implemented"))
}

func (UnimplementedNotificationServiceHandler) UpdatePreferences(context.Context, *connect.Request[v1.UpdatePreferencesRequest]) (*connect.Response[v1.UpdatePreferencesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rootstock.v1.NotificationService.UpdatePreferences is not implemented"))
}

// AdminServiceClient is a client for the rootstock.v1.AdminService service.
type AdminServiceClient interface {
	SuspendByClass(context.Context, *connect.Request[v1.SuspendByClassRequest]) (*connect.Response[v1.SuspendByClassResponse], error)
}

// NewAdminServiceClient constructs a client for the rootstock.v1.AdminService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAdminServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AdminServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	adminServiceMethods := v1.File_rootstock_v1_rootstock_proto.Services().ByName("AdminService").Methods()
	return &adminServiceClient{
		suspendByClass: connect.NewClient[v1.SuspendByClassRequest, v1.SuspendByClassResponse](
			httpClient,
			baseURL+AdminServiceSuspendByClassProcedure,
			connect.WithSchema(adminServiceMethods.ByName("SuspendByClass")),
			connect.WithClientOptions(opts...),
		),
	}
}

// adminServiceClient implements AdminServiceClient.
type adminServiceClient struct {
	suspendByClass *connect.Client[v1.SuspendByClassRequest, v1.SuspendByClassResponse]
}

// SuspendByClass calls rootstock.v1.AdminService.SuspendByClass.
func (c *adminServiceClient) SuspendByClass(ctx context.Context, req *connect.Request[v1.SuspendByClassRequest]) (*connect.Response[v1.SuspendByClassResponse], error) {
	return c.suspendByClass.CallUnary(ctx, req)
}

// AdminServiceHandler is an implementation of the rootstock.v1.AdminService service.
type AdminServiceHandler interface {
	SuspendByClass(context.Context, *connect.Request[v1.SuspendByClassRequest]) (*connect.Response[v1.SuspendByClassResponse], error)
}

// NewAdminServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAdminServiceHandler(svc AdminServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	adminServiceMethods := v1.File_rootstock_v1_rootstock_proto.Services().ByName("AdminService").Methods()
	adminServiceSuspendByClassHandler := connect.NewUnaryHandler(
		AdminServiceSuspendByClassProcedure,
		svc.SuspendByClass,
		connect.WithSchema(adminServiceMethods.ByName("SuspendByClass")),
		connect.WithHandlerOptions(opts...),
	)
	return "/rootstock.v1.AdminService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AdminServiceSuspendByClassProcedure:
			adminServiceSuspendByClassHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAdminServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAdminServiceHandler struct{}

func (UnimplementedAdminServiceHandler) SuspendByClass(context.Context, *connect.Request[v1.SuspendByClassRequest]) (*connect.Response[v1.SuspendByClassResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rootstock.v1.AdminService.SuspendByClass is not implemented"))
}
