services:
  zitadel-postgres:
    restart: unless-stopped
    image: postgres:17
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d zitadel -U postgres"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 20s
    networks:
      - rootstock
    volumes:
      - zitadel-postgres-data:/var/lib/postgresql/data:rw

  app-postgres:
    restart: unless-stopped
    image: timescale/timescaledb:latest-pg17
    command: ["postgres", "-c", "shared_preload_libraries=timescaledb"]
    environment:
      PGUSER: rootstock
      POSTGRES_USER: rootstock
      POSTGRES_PASSWORD: rootstock
      POSTGRES_DB: rootstock
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d rootstock -U rootstock"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 20s
    networks:
      - rootstock
    volumes:
      - app-postgres-data:/var/lib/postgresql/data:rw

  dgraph-zero:
    restart: unless-stopped
    image: dgraph/dgraph:v24.0.5
    command: dgraph zero --my=dgraph-zero:5080
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:6080/health || exit 1"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 20s
    networks:
      - rootstock
    volumes:
      - dgraph-zero-data:/dgraph

  dgraph-alpha:
    restart: unless-stopped
    image: dgraph/dgraph:v24.0.5
    command: dgraph alpha --my=dgraph-alpha:7080 --zero=dgraph-zero:5080 --security whitelist=0.0.0.0/0
    depends_on:
      dgraph-zero:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8080/health || exit 1"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 20s
    networks:
      - rootstock
    volumes:
      - dgraph-alpha-data:/dgraph

  maildev:
    restart: unless-stopped
    image: maildev/maildev:2.2.1
    environment:
      MAILDEV_BASE_PATHNAME: /maildev
    networks:
      - rootstock

networks:
  rootstock:
    name: rootstock

volumes:
  zitadel-postgres-data:
  app-postgres-data:
  dgraph-zero-data:
  dgraph-alpha-data:
